services:
  - type: web
    name: express-tidb-api
    runtime: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
      - key: DB_HOST
        fromDatabase:
          name: tidb-cloud-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: tidb-cloud-db
          property: port
      - key: DB_USER
        fromDatabase:
          name: tidb-cloud-db
          property: user
      - key: DB_PASSWORD
        sync: false 
      - key: DB_NAME
        fromDatabase:
          name: tidb-cloud-db
          property: database
